version: '3'

services:
 
  app:
    build: 
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: npm run dev # start
    networks: 
      - desafio02-network
    tty: true
    volumes: # Durante desenvolvimento
      - ./node/src:/usr/app/src
    ports: 
      - "3000:3000"
    depends_on: 
       - db

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes: 
      - ./mysql/init/init.sql:/data/application/init.sql
      - ./mysql/data:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=desafio02db
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - desafio02-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    networks: 
      - desafio02-network

networks: 
  desafio02-network:
    driver: bridge      